version: '3.7'
services:
  backend:
    build: '.'
    command: npm run dev
    restart: always
    ports:
      - '3333:3333'
    volumes:
      - type: bind
        source: .
        target: /backend/user/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: NG
    ports:
      - "5432:5432"
